import type { Metadata } from "next";
// src/app/layout.js
import '@/styles/globals/global.scss';
import Header from '@/src/components/Header';
import Footer from '@/src/components/Footer';



export const metadata: Metadata = {
  title: "Totee Block",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <Header />
        <div className="contentArea">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
